### PR TITLE
Add lint static code analysis for python and ipynb files

### PR DESCRIPTION
**Pull request by CaiqueCoelho**
## What does this PR do?

This GitHub Action workflow will:

1. Trigger on every push and pull request to the repository.
2. Set up a Python environment.
3. Install flake8 and nbqa
4. Run flake8 and nbqa on your codebase.
 
### Commit and push your changes:
After adding the .github/workflows/lint.yml file, commit and push it to your repository. Once it's pushed, GitHub Actions will start running the flake8 linting checks on every push or pull request.

### Monitor the GitHub Actions tab:
After pushing, you can navigate to the "Actions" tab on your GitHub repository to see the status of the checks. If flake8 finds any issues, they will be reported there, and the action might fail, indicating that there are linting errors in the codebase.

By following these steps, you've now integrated PEP-8 static code analysis into your GitHub repository using GitHub Actions and flake8.

## Related PRs and Issues is any
#11 

### Have you read the Contributing Guidelines?

- [x] yes
- [ ] no

### Is the code your own?
 
- [x] yes
- [ ] no

### Is the code named with proper file extension (eg. `.py` for python, `.java` for java and `.cpp` for c plus plus) ?
 
- [x] yes
- [ ] no

### Is your code in proper folder and proper subfolder?
 
- [x] yes
- [ ] no

### Have you added the documentation/nformation related to your code in the corresponding subfolder?
 
- [x] yes
- [ ] no

### Have you made or updated corresponding README.md file in the folder?
 
- [x] yes
- [ ] no
 
### Is the code beautified?

- [x] yes
- [ ] no

### Is the code clear to understand with proper variable naming and comments?

- [x] yes
- [ ] no

### CODE REVIEW

**Comment by CaiqueCoelho** [comment]
Hey @Aatmaj-Zephyr could you review, please? Also, I would be very happy if this PR could be part of Hacktoberfest please

**Comment by CaiqueCoelho** [comment]
Running this on my fork to see the job execution I saw some valid feedbacks from the lint we should address 👯 
https://github.com/CaiqueCoelho/handtype/actions/runs/6667984549/job/18122554826?pr=1
I can work on fixing those lint feedbacks in another PR if you want

**Comment by Aatmaj-Zephyr** [comment]
> Running this on my fork to see the job execution I saw some valid feedbacks from the lint we should address 👯 https://github.com/CaiqueCoelho/handtype/actions/runs/6667984549/job/18122554826?pr=1 I can work on fixing those lint feedbacks in another PR if you want

sure

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Accepted

**Pull request merged**
